// Licensed under the Apache-2.0 license

//! Certificate Store Platform Implementation
//! 
//! Provides certificate management using static certificates with ECDSA signing

use std::sync::Mutex;

#[cfg(feature = "crypto")]
use p384::{
    ecdsa::{SigningKey, Signature, signature::Signer}, 
    SecretKey
};

use spdm_lib::cert_store::{SpdmCertStore, CertStoreResult, CertStoreError};
use spdm_lib::protocol::algorithms::{AsymAlgo, ECC_P384_SIGNATURE_SIZE, SHA384_HASH_SIZE};
use spdm_lib::protocol::certs::{CertificateInfo, KeyUsageMask};
use super::certs::{STATIC_ROOT_CA_CERT, STATIC_ATTESTATION_CERT, STATIC_CERTIFICATE_CHAIN};

/// Certificate store with proper ECDSA signing
pub struct DemoCertStore {
    cert_chain: Vec<u8>,
    #[cfg(feature = "crypto")]
    signing_key: Mutex<Option<SigningKey>>,
}

impl DemoCertStore {
    pub fn new() -> Self {
        #[cfg(feature = "crypto")]
        {
            println!("Loading static certificate chain...");
            let (cert_chain, signing_key) = Self::generate_certificate_chain();
            println!("Static certificate chain loaded successfully");
            
            Self {
                cert_chain,
                signing_key: Mutex::new(Some(signing_key)),
            }
        }
        
        #[cfg(not(feature = "crypto"))]
        {
            // Fallback for when crypto feature is not enabled
            let cert_chain = b"DEMO_CERTIFICATE_CHAIN_DATA".to_vec();
            Self { cert_chain }
        }
    }

    #[cfg(feature = "crypto")]
    fn generate_certificate_chain() -> (Vec<u8>, SigningKey) {
        use rand::rngs::OsRng;
        
        // Use static certificates generated by OpenSSL
        println!("Using static OpenSSL-generated certificates");
        
        // Convert the static certificate chain to Vec<u8>
        let cert_chain = STATIC_CERTIFICATE_CHAIN.to_vec();
        
        // Generate a key for signing (we can't extract the key from certificates)
        let attestation_key = SecretKey::random(&mut OsRng);
        let attestation_signing_key = SigningKey::from(&attestation_key);
        
        println!("Certificate chain loaded: {} bytes", cert_chain.len());
        println!("Root CA certificate: {} bytes", STATIC_ROOT_CA_CERT.len());
        println!("Attestation certificate: {} bytes", STATIC_ATTESTATION_CERT.len());
        
        (cert_chain, attestation_signing_key)
    }

    /// Extract the first certificate from a DER-encoded certificate chain
    #[allow(dead_code)]
    fn extract_first_certificate_der<'a>(&self, cert_chain: &'a [u8]) -> Option<&'a [u8]> {
        if cert_chain.len() < 2 {
            return None;
        }
        
        let mut offset = 0;
        
        // Check for SEQUENCE tag (0x30)
        if cert_chain[offset] != 0x30 {
            return None;
        }
        offset += 1;
        
        // Parse length and calculate total certificate size
        let (content_length, header_size) = if cert_chain[offset] & 0x80 == 0 {
            // Short form length (0-127)
            let content_len = cert_chain[offset] as usize;
            let header_len = 2; // tag + 1 byte length
            (content_len, header_len)
        } else {
            // Long form length
            let length_octets = (cert_chain[offset] & 0x7f) as usize;
            if length_octets == 0 || length_octets > 4 {
                return None;
            }
            offset += 1;
            
            if offset + length_octets > cert_chain.len() {
                return None;
            }
            
            let mut content_len = 0;
            for i in 0..length_octets {
                content_len = (content_len << 8) | cert_chain[offset + i] as usize;
            }
            
            let header_len = 2 + length_octets; // tag + length indicator + length bytes
            (content_len, header_len)
        };
        
        let total_cert_size = header_size + content_length;
        
        if total_cert_size > cert_chain.len() {
            return None;
        }
        
        Some(&cert_chain[0..total_cert_size])
    }
}

impl SpdmCertStore for DemoCertStore {
    fn slot_count(&self) -> u8 {
        1 // Only support slot 0
    }

    fn is_provisioned(&self, slot_id: u8) -> bool {
        slot_id == 0 // Only slot 0 is provisioned
    }

    fn cert_chain_len(&mut self, _asym_algo: AsymAlgo, slot_id: u8) -> CertStoreResult<usize> {
        if slot_id == 0 {
            Ok(self.cert_chain.len())
        } else {
            Err(CertStoreError::InvalidSlotId)
        }
    }

    fn get_cert_chain<'a>(
        &mut self,
        slot_id: u8,
        _asym_algo: AsymAlgo,
        offset: usize,
        cert_portion: &'a mut [u8],
    ) -> CertStoreResult<usize> {
        if slot_id != 0 {
            return Err(CertStoreError::InvalidSlotId);
        }

        if offset >= self.cert_chain.len() {
            return Ok(0);
        }

        let remaining = self.cert_chain.len() - offset;
        let copy_len = remaining.min(cert_portion.len());

        cert_portion[..copy_len].copy_from_slice(&self.cert_chain[offset..offset + copy_len]);
        Ok(copy_len)
    }

    fn root_cert_hash<'a>(
        &mut self,
        slot_id: u8,
        _asym_algo: AsymAlgo,
        cert_hash: &'a mut [u8; SHA384_HASH_SIZE],
    ) -> CertStoreResult<()> {
        if slot_id != 0 {
            return Err(CertStoreError::InvalidSlotId);
        }

        // For demo: simple hash of the first bytes
        for (i, byte) in cert_hash.iter_mut().enumerate() {
            *byte = self.cert_chain.get(i % self.cert_chain.len()).copied().unwrap_or(0);
        }

        Ok(())
    }

    fn sign_hash<'a>(
        &self,
        slot_id: u8,
        hash: &'a [u8; SHA384_HASH_SIZE],
        signature: &'a mut [u8; ECC_P384_SIGNATURE_SIZE],
    ) -> CertStoreResult<()> {
        if slot_id != 0 {
            return Err(CertStoreError::InvalidSlotId);
        }

        #[cfg(feature = "crypto")]
        {
            if let Ok(signing_key_guard) = self.signing_key.lock() {
                if let Some(ref signing_key) = *signing_key_guard {
                    let sig: Signature = signing_key.sign(hash);
                    let sig_bytes = sig.to_bytes();
                    if sig_bytes.len() <= ECC_P384_SIGNATURE_SIZE {
                        signature[..sig_bytes.len()].copy_from_slice(&sig_bytes);
                        return Ok(());
                    }
                }
            }
            Err(CertStoreError::PlatformError)
        }
        
        #[cfg(not(feature = "crypto"))]
        {
            // Fallback for demo without crypto
            for (i, byte) in signature.iter_mut().enumerate() {
                *byte = hash[i % SHA384_HASH_SIZE] ^ ((i as u8).wrapping_mul(73));
            }
            Ok(())
        }
    }

    fn key_pair_id(&self, slot_id: u8) -> Option<u8> {
        if slot_id == 0 { Some(1) } else { None }
    }

    fn cert_info(&self, slot_id: u8) -> Option<CertificateInfo> {
        if slot_id != 0 {
            return None;
        }

        let mut cert_info = CertificateInfo(0);
        cert_info.set_cert_model(1);
        Some(cert_info)
    }

    fn key_usage_mask(&self, slot_id: u8) -> Option<KeyUsageMask> {
        if slot_id != 0 {
            return None;
        }

        let mut key_usage = KeyUsageMask::default();
        key_usage.set_challenge_usage(1);
        key_usage.set_measurement_usage(1);
        Some(key_usage)
    }
}