name: Build SPDM Emulator Artifacts

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Commit hash to build spdm-emu from'
        required: true
        type: string

jobs:
  build-emu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DMTF spdm-emu
        uses: actions/checkout@v4
        with:
          repository: DMTF/spdm-emu
          ref: ${{ inputs.commit_hash }}
          submodules: recursive
          path: spdm-emu
    
      - name: Install build dependecies
        run: |
            sudo apt install -y build-essential

      - name: Build application and prepare release
        run: |
            cd "$GITHUB_WORKSPACE"/spdm-emu
            git submodule update
            mkdir build -p && cd build
            cmake -DARCH=x64 -DTOOLCHAIN=GCC -DTARGET=Debug -DCRYPTO=openssl ..
            make copy_sample_key
            make -j
          
      - name: Create or update release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir "$GITHUB_WORKSPACE"/emu
          cp "$GITHUB_WORKSPACE"/spdm-emu/build/bin/spdm_requester_emu spdm-emu/build/bin/spdm_responder_emu "$GITHUB_WORKSPACE"/emu
          
          gh release delete spdm-emu --yes --repo ${{ github.repository }} || true
          
          gh release create spdm-emu \
            --repo ${{ github.repository }} \
            --title "SPDM Emulators (built from ${{ inputs.commit_hash }})" \
            --notes "Built from commit: ${{ inputs.commit_hash }}" \
            --prerelease \
            "$GITHUB_WORKSPACE"/emu/*
